# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerieTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('productora', models.CharField(max_length=10)),
                ('fecha_publicacion', models.IntegerField()),
                ('temporadas', models.IntegerField()),
                ('genero', models.IntegerField(choices=[(0, 'Ciencia Ficcion'), (1, 'Comedia'), (2, 'Policiaca'), (3, 'Terror'), (4, 'Animacion'), (5, 'Accion'), (6, 'Drama'), (7, 'Romance'), (8, 'Documental'), (9, 'Historia')])),
                ('estado', models.IntegerField(choices=[(0, 'En produccion'), (1, 'En emision'), (2, 'Finalizada'), (3, 'Cancelada')])),
            ],
        ),
    ]
